[project]
name = "my_project"
version = "0.1.0"
description = "My project"
dependencies = [
    "colorama>=0.4.6"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"